# Generated by Django 4.2 on 2025-02-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper_app', '0002_job_description_alter_job_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True, default='https://example.com/default-job', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
